Polishing

diff --git a/internet b/internet
--- a/internet
+++ b/internet
@@ -10,51 +10,53 @@ get_wifi_list(){ #{{{
   printf "SrNo\t$(echo "$list" | sed '1p;d')\n"
   wifi_list_show=$(echo "$list" | sed '1d' | awk '{print ++i")" "\t" $0}')
   echo "$wifi_list_show"
-  wifi_ssid=$(nmcli -t -f ssid dev wifi list)
+} #}}}
+
+get_wifi_name(){ #{{{
+  local __wifi_name=$1
+
+  read -p "Enter SrNO, r to refresh or q to quit: " srno
+  [[ -z $srno || ! $srno =~ [0-9]+ ]] && (echo $srno;echo "Sr no. is invalid")
+  [[ $srno == q ]] && (eval $__wifi_name="'q'"; return)
+  [[ $srno == r ]] && (eval $__wifi_name="'r'"; return)
+
+  local wifi_ssid=$(nmcli -t -f ssid dev wifi list)
+  local __name=$(echo -e "$wifi_ssid" | sed -e "${srno}p;d")
+  [[ -z "$__name" ]] && echo SrNo. $srno is invalid || eval $__wifi_name="'$__name'"; return
 } #}}}
 
 connect_wifi(){ #{{{
   # To check if the wifi is connected to the desired network or no network at all
-  while [[ "$active" != "$wifi_name" || "$active" == None ]]
-  do
-      # To scan for new networks in case of a rescan
+  while [[ "$active" != "$wifi_name" || "$active" == None ]]; do
+    # To scan for new networks in case of a rescan
     nmcli device wifi rescan 2> /dev/null
-    #clear
-      # Time required for a rescan to complete
+    # Time required for a rescan to complete or waiting in case of high cpu usage
     sleep 5
-      # List available wifi networks
-      get_wifi_list
-#    nmcli device wifi list
-    read -p "Enter SrNO, r to refresh or q to quit: " srno
-    if [[ $srno == q ]];then
-      exit 1
-    elif [[ $srno == r ]];then
-      continue
-    fi
-    wifi_name=$(echo -e "$wifi_ssid" | sed -e "${srno}p;d")
-    if [[ -z "$wifi_name" ]];then
-      echo SrNo. is empty
-      continue
-    fi
-    get_active
-    if [ "$active" == "$wifi_name" ];then
-      echo Already connected to "$wifi_name"
-      exit 1
-    fi
+    # List available wifi networks
+    get_wifi_list
+    # Get SSID
+    get_wifi_name wifi_name
+
+    [[ $wifi_name == q ]] && exit
+    [[ $wifi_name == r ]] && continue
     echo Selected network: "$wifi_name"
 
-    # Connecting{{{
-      # To check if a connection is already configured or not
+    get_active
+    if [[ $active == $wifi_name ]];then
+      echo Currently connected to "$wifi_name"
+      return
+    fi
+
+    # To check if a connection is already configured or not
     if [[ ! -z "$( echo "$connections" | grep -e "$wifi_name" )" ]];then
-        # If the wifi is connected to any network by default it needs to close that connection
+      # If the wifi is connected to any network by default it needs to close that connection
       get_active
       [[ "$active" == None ]] && : ||  $(nmcli connection down "$active" > /dev/null)
-        # If the network is previously configured then activate the connection.
+      # If the network is previously configured then activate the connection.
       nmcli --ask connection up "$wifi_name" > /dev/null
     else
       nmcli --ask dev wifi connect "$wifi_name" > /dev/null
     fi
-    #}}}
 
     get_active
     if [[ "$active" == "$wifi_name" ]];then
@@ -84,6 +86,8 @@ get_active
 connections=$(nmcli -f name connection show | sed '1d')
 # getting the interface (wifi/lan) which is active at the moment
 interface=$( ip route | awk '/^default/ {print $5}' )
+lan_in="enp3s0"
+wifi_in="wlp2s0"
 #}}}
 
 # Main {{{
@@ -91,16 +95,15 @@ if [[ $1 == "" ]];then
   echo "$active"
 
 elif [[ $1 == refresh ]];then
-  if [[ $interface == enp3s0 ]];then
+  if [[ $interface == $lan_in ]];then
     lan_refresh $interface
-  elif [[ $interface == wlp2s0 ]];then
+  elif [[ $interface == $wifi_in ]];then
     wifi_refresh
   fi
 
 elif [[ $1 == wifi ]];then
   nmcli radio wifi on
   # Sometimes the wifi gets connected to a network which is preconfigured, automatically
-  sleep 6
   get_active
   if [[ "$active" == None ]];then
     connect_wifi
@@ -113,9 +116,9 @@ elif [[ $1 == lan ]];then
   # If the interface is enp3s0 then do nothing
   # If the no wifi active then do nothing
   # Or else disconnect with that wifi
-  [[ $interface == "enp3s0" ]] && exit 1
+  [[ $interface == $lan_in ]] && exit 1
     #[[ ! $iterface == enp3s0 ]] && $([[ -z "$active" || "$active" == None || "$active" == Wired ]] && nmcli con down "$active")
-    nmcli dev disconnect wlp2s0
-    nmcli dev con enp3s0
+    nmcli dev disconnect $wifi_in
+    nmcli dev con $lan_in
 fi
 #}}}
